spring:
  application:
    name: service2
server:
  port: 8020

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      serviceName: service2
      version: v1.0.0
      serviceDepencies:
        service1: v1.0.0, v1.1.0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka
